"""Data models for the quiz grading tool.

All entities are Python dataclasses for simplicity (Constitution Principle I).
JSON serialization uses dataclasses.asdict() with ISO 8601 datetime strings.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional


# ---------------------------------------------------------------------------
# Configuration entities (loaded from YAML)
# ---------------------------------------------------------------------------

@dataclass
class PatternDef:
    regex: str
    weight: float
    description: str
    negative: bool = False


@dataclass
class ExpectedResult:
    result_id: str
    description: str
    columns: list[str]
    rows: list[dict]
    float_tolerance: float = 0.1
    row_order_matters: bool = False


@dataclass
class CriterionConfig:
    criterion_id: str
    name: str
    points: int
    type: str  # "pattern", "execution", "subjective"
    patterns: list[PatternDef] = field(default_factory=list)
    expected_result_ref: Optional[str] = None
    rubric_text: Optional[str] = None


@dataclass
class TaskConfig:
    task_id: str
    task_name: str
    points: int
    section_marker: str  # regex pattern (pipe-delimited alternatives)
    criteria: list[CriterionConfig] = field(default_factory=list)
    expected_results: list[ExpectedResult] = field(default_factory=list)


@dataclass
class QuizConfig:
    quiz_id: str
    quiz_name: str
    total_points: int
    database: str
    submission_dir: str
    submission_glob: str
    exclude_patterns: list[str]
    tasks: list[TaskConfig]


# ---------------------------------------------------------------------------
# Submission entities (discovered from filesystem)
# ---------------------------------------------------------------------------

@dataclass
class Submission:
    student_name: str
    file_path: str
    submitted_at: Optional[datetime] = None
    is_duplicate: bool = False


@dataclass
class TaskContent:
    task_id: str
    sql_queries: list[str] = field(default_factory=list)
    comments: str = ""
    insight_text: str = ""
    raw_text: str = ""


@dataclass
class ParsedSubmission:
    submission: Submission
    tasks: list[TaskContent] = field(default_factory=list)
    is_blank: bool = False
    parse_warnings: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Grading result entities (generated by pipeline stages)
# ---------------------------------------------------------------------------

@dataclass
class CriterionResult:
    criterion_id: str
    score: int
    max_points: int
    source: str  # "pattern", "execution", "llm", "manual", "skipped"
    details: str = ""
    confidence: str = "deterministic"
    feedback: str = ""
    flagged: bool = False
    flag_reason: str = ""


@dataclass
class Override:
    criterion_id: str
    original_score: int
    new_score: int
    reason: str = ""


@dataclass
class TaskGrade:
    task_id: str
    criteria_results: list[CriterionResult] = field(default_factory=list)
    task_score: int = 0
    task_max: int = 0


@dataclass
class GradeReport:
    student_name: str
    submission: Submission
    task_grades: list[TaskGrade] = field(default_factory=list)
    total_score: int = 0
    total_max: int = 0
    instructor_notes: str = ""
    reviewed: bool = False
    reviewed_at: Optional[datetime] = None
    overrides: list[Override] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Session persistence (for resume capability)
# ---------------------------------------------------------------------------

@dataclass
class GradingSession:
    session_id: str
    quiz_id: str
    config_path: str
    started_at: datetime
    last_updated: datetime
    status: str = "in_progress"  # "in_progress" or "completed"
    students_total: int = 0
    students_reviewed: int = 0
    current_index: int = 0
    grade_reports: list[GradeReport] = field(default_factory=list)
